### PR TITLE
JB::AdminPlugin & Admin Refactoring

### PR DESCRIPTION
**Pull request by eriknelson**
PR for #60

Unblocks #59

### CODE REVIEW

**Comment by s0ph0s-2** [comment]
I'll update my PR to use the new AdminPlugin, as well as parse the commands in a more conventional way.

**Comment by rikai** [comment]
Mmm, just a small note or two...

I think "auth" might be more appropriate name for the containing location than "jb".

Secondly, it might be nice for us to start using the locale functionality i've already mostly finished on the web side to start abstracting the text strings out of the plugins.

If you're in the mood to include that work in the PR, it'd be wonderful, but if you're not, i'll accept it anyway. ;)

**Comment by eriknelson** [comment]
:+1: Will update!

**Comment by rikai** [comment]
Closes #60

**Pull request merged**
