### PR TITLE
Feature/live quotes editing

### PR DESCRIPTION
**Pull request by s0ph0s-2**
This pull request aims to add live editing to the quotes plugin. This enables the bot owner and, optionally, channel operators, to add quotes to the quote list, without manually editing `quotes.yml`.  
It also moves the file handling code into the data model, abstracting it away from the view.

If you don't want this as part of canonical Showbot, that's fine. I wrote it mostly for practice, since I only learned Ruby last Sunday.

-s0ph0s

### CODE REVIEW

**Comment by rikai** [comment]
Discussion on the PR from IRC:
<nelsk> PR looks okay to me, the one change I'd make is I think cinchize had a framework supported way for parsing commands iirc
<nelsk> The matcher supports argument extraction.

[See example here](https://github.com/s0ph0s-2/Showbot/blob/7a3755d3667cef57eaf58ad09b516ed491a5f030/lib/cinch/plugins/quotes.rb#L21).

<rikai> The main improvment i can see is that we need a central source to pull the list of valid users with access to a command. It's already been implemented in admin.rb, and a second implementation is being added here.
<rikai> Maybe need a shared resource that has subsections for commands that can have users added to that array, and if the array is empty, it defaults to a 'default', also definable, array of nicks.
<rikai> I also don't think has_ns, is really needed, and allow_op_msgs seems redundant. Really my main complaint is it feels like things that already exist in the bot are being reimplemented, rather than absracting some of the stuff from admin.rb out to be reusable across plugins.

<rikai> Yeah, the approach up until now has been to just stuff anything that needs auth into admin.rb. But moving stuff out into a more generalized space would be the proper solution. :P

**Comment by eriknelson** [comment]
[Argument extraction example in the DO bot functions](https://github.com/rikai/Showbot/blob/a6655ac6fcd608ba77e04a375893928a2221bef5/lib/cinch/plugins/admin.rb#L16)

Regex groups get passed through.

**Comment by s0ph0s-2** [comment]
And that fixes it to use the admin plugin. Non-exhaustive testing shows it to work properly in most normal cases.

**Comment by rikai** [comment]
Looks good!

**Pull request merged**
